		stats: {
			strength: x,
	        dexterity: x,
	        constitution: x,
	        intelligence: x,
	        wisdom: x,
	        charisma: x,
			race: human,
			alignment:  "Neutral Good",
			patronDeity: "USERINFO",
			"ARMORCLASS": "USERINFO",
			"HIT POINTS": "USERINFO",
			"Character Name":"USERINFO",
			Birthdate:"USERINFO",
			birthRank:"USERINFO",
			playerName:"USERINFO",
			age:"USERINFO",
			sex:"USERINFO",
			height:"USERINFO",
			weight:"USERINFO",
			hair:"USERINFO",
			eyes:"USERINFO",
			skin:"USERINFO",
			vision:"USERINFO",
			personality:"USERINFO",
			origin:"USERINFO",
		},
		
